%YAML 1.2
---
gpu: 3

dataset:
  input_train: '/finaldata/elo_ranges/1800/train/*/*'
  input_test: '/finaldata/elo_ranges/1800/test/*/*'

training:
    precision: 'half'
    batch_size: 1024
    num_batch_splits: 1
    test_steps: 2000
    train_avg_report_steps: 50
    total_steps: 400000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        - 0.1
        - 0.01
        - 0.001
        - 0.0001
    lr_boundaries:
        - 80000
        - 200000
        - 360000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
